### ISSUE TITLE
Downloading video to .mp4 file sound missing

### ISSUE THREAD

**Issue by chrisVillanueva** [fent/node-ytdl#169]
Not sure if this a recent bug. I just updated to @latest.  I download a video and define the output file as  `> video.mp4`.  Download is successful, but there is no sound. I tested the file with two MP4 players--same result.

**Comment by redbrain** [comment]
What options are you using to download the video?
Are you certain that its ytdl-core dependency is also on latest?

**Comment by TimeForANinja** [comment]
if you actually used `ytdl https://www.youtube.com/watch?v=xxxxxx > video.mp4` you only saved the informational logs
you should use `ytdl --output video.mp4 https://www.youtube.com/watch?v=xxxxxx`

**Comment by fent** [comment]
> if you actually used `ytdl https://www.youtube.com/watch?v=xxxxxx > video.mp4` you only saved the informational logs
> you should use `ytdl --output video.mp4 https://www.youtube.com/watch?v=xxxxxx`

the first one should work too. ytdl detects if the stdout is a "mutable" shell, if it is it prints a progress bar, otherwise it writes the file to it.

anyway, if this happens for every video, i'd look at the options given. otherwise, it's possible but rare to get a video without audio without any filtering options given

**Comment by fent** [comment]
going to close this since this is how youtube stores most of its formats, with separate audio/video files. you can specify that it has both with `filter = audioandvideo`. you'll get a format that has both, although at low video quality 360p or 720p.
